/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense_1.h"
#include "CapSense_1_Control.h"
#include "CapSense_1_Filter.h"
#include "CapSense_1_Processing.h"
#include "CapSense_1_Sensing.h"
#include "CapSense_1_Structure.h"
#include "CapSense_1_Tuner.h"
#include "CapSense_1_Configuration.h"
#include "CapSense_1_SensingCSD_LL.h"
#include "CapSense_1_RegisterMap.h"
#include "CapSense_1_Centroid_LL.h"
#include "CapSense_1_SmartSense_LL.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "Clock_1.h"
#include "PWM_1.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "CapSense_1_ISR.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

