# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\ubald\Documents\PSoC Creator\Ejercicio4\Servo.cydsn\Servo.cyprj
# Date: Tue, 28 Dec 2021 14:51:21 GMT
#set_units -time ns
create_clock -name {CapSense_1_ModClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {Clock_1(FFB)} -period 500 -waveform {0 250} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {UART_1_SCBCLK(FFB)} -period 708.33333333333326 -waveform {0 354.166666666667} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_1_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 13 25} [list]
create_generated_clock -name {UART_1_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 17 35} -nominal_period 708.33333333333326 [list]


# Component constraints for C:\Users\ubald\Documents\PSoC Creator\Ejercicio4\Servo.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\ubald\Documents\PSoC Creator\Ejercicio4\Servo.cydsn\Servo.cyprj
# Date: Tue, 28 Dec 2021 14:51:19 GMT
